### ISSUE TITLE
Error while installing RFM-PHP with Laravel 5.4

### ISSUE THREAD

**Issue by hungnm144** [servocoder/RichFilemanager-PHP#10]
![image](https://user-images.githubusercontent.com/1074467/29503239-2165d10a-8660-11e7-9bd2-e0c43e8ea529.png)

I'm using Laravel 5.4 and installing RFM-PHP but this error was displayed. Please help, Thanks!
@servocoder please help

**Comment by servocoder** [comment]
RFM shares some packages with Laravel, but restricts version of these packages in the `composer.json` file to meet PHP 5.4 requirement. I think this is the reason of the conflict.

For your particular case you can edit the `composer.json` file and bump version to "5.4.\*" instead of "5.2.\*" for all "illuminate/*" packages. Let me know if this will work for you.

**Comment by hungnm144** [comment]
@servocoder 
I've installed successfully RFM with Laravel 5.4. Edit the composer.json and bump version to "5.4.*". And I've found a function `logger()` in `/src/helper.php` in conflict with laravel 5.4.  Because in Laravel 5.4, The logger function is available. [https://laravel.com/docs/5.4/helpers#method-logger](url)
I have edited it. And it worked normally

**Comment by servocoder** [comment]
Thanks for sharing the solution!

**Comment by eqxDev** [comment]
Trying to do this but cannot seem to get this working...

"require": {
        "php": ">=5.6.4",
        "barryvdh/laravel-ide-helper": "^2.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.4"
    },

This is everything my composer requires. So everything is 5.4, Yet when I install I still get that error @hungnm144 posted. Any help would be great.

Thank you.

**Comment by servocoder** [comment]
I haven't tested it yet, but I assume @hungnm144 adjusted the `composer.json` file of the RFM project and update dependencies after that. 

@hungnm144 can you clarify this point and provide the content of your `composer.json` file. Thanks

**Comment by hungnm144** [comment]
I've forked your package at here: [](https://github.com/hungnm144/RichFilemanager-PHP)
And I've published this package to Packagist.
Run `composer require hungnm144/richfilemanager-php:dev-master` to test it with Laravel 5.4.

**Comment by servocoder** [comment]
@hungnm144 @vocjunior thanks for your contribution.
 I have wrapped functions with RFM namespace and going to release this in the next version.

**Comment by servocoder** [comment]
Released in v.1.1.2
