### ISSUE TITLE
Symlinks to outside of the storage root does not work

### ISSUE THREAD

**Issue by hanimayahi** [servocoder/RichFilemanager-PHP#12]
Say I have this folder structure

```
files 
│
└─── shared
│   
└───users
    │
    └───1 (user 1's root folder)
        └─── shared -> ../../shared
    └───2 (user 2's root folder)
        └─── shared -> ../../shared
    └─── etc
```

Trying to traverse the symlink from a users root directory will return the error `The directory /shared/ does not exist.` 

This error occurs in ItemModel::isValidPath(). The function uses the storage root, being /files/users/:id in this example, and the realpath of the folder is /files/shared, resulting in the $rpSubstr variable not matching $rpFiles.

What I want to do can be done client side, setting the storage root folder to /files/, and using the query parameter exclusiveFolder=/users/1/ will show the filemanager the way I intended and symlinks will work outside of the exclusive folder. However there seems to be no current way to set a exclusiveFolder from serverside.

I'm not sure what would be the most efficient way to fix this, currently to solve this for my project I have the ItemModel::isValidPath() function to use /files/ as rootPath. It'd be great if it was possible to configure a exclusiveFolder from server side.

**Comment by servocoder** [comment]
It would be very unsecure to allow symlinks that point to ANY target files/folders outside fileroot folder. Thus I have added "security.symlinks" configuration section in the `config.local.php` file where you can either allow all symlinks at your own risk or specify whilelist of paths for symlink targets.
