### ISSUE TITLE
Please add SSE AES256 option

### ISSUE THREAD

**Issue by hegyre** [servocoder/RichFilemanager-PHP#14]
Hello guys,
I found an issue where we cannot upload files on S3 because the S3 bucket has enforced the AES256 encryption (the bucket denies uploads without this)
See http://s3tools.org/kb/item11.htm for full bucket policy

I digged a bit, and it appears (but I may be wrong) that we should have a new option there:
https://github.com/servocoder/RichFilemanager-PHP/blob/master/src/Repository/S3/UploadHandler.php

around lines 273 and 285

Adding the following so for multi part and non-multi part
'ServerSideEncryption' => 'AES256',
You can find docu here: http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobject

Even better to make it optionnal via the config file
https://github.com/servocoder/RichFilemanager-PHP/blob/master/src/config/config.s3.php

**Comment by servocoder** [comment]
Implemented in v.1.1.1, update the package via `composer update`
https://github.com/servocoder/RichFilemanager-PHP/blob/master/src/config/config.s3.php#L66

You can now define `encryption` config option in the `filemanager.php` entrypoint script. For instance:

```php
...
$config['credentials'] = [/*your AWS credentials here*/];
$config['encryption'] = 'AES256';

$s3 = new \RFM\Repository\S3\Storage($config);
...
```

Any feedback is welcome.
