### ISSUE TITLE
Generate S3 URL's

### ISSUE THREAD

**Issue by JjamesS** [servocoder/RichFilemanager-PHP#16]
I am able to connect to S3 without issue, but no matter the config I use it will not generate an S3 URL it always uses the connector. Is there an example that shows proper setup to generate AWS S3 URL's?

**Comment by servocoder** [comment]
Technically it's possible, but specify at what exact point you expect RFM to generate S3 URL instead of the connector URL. It's important thing to understand in order to provide a relevant answer.

Anyway you should understand that this will work only if your S3 obects are public.

**Comment by JjamesS** [comment]
That solved it.

**Comment by JjamesS** [comment]
Is there any way to set this at runtime in the PHP connector?
in `filemanager.config.json`
```
    "viewer": {
        "absolutePath": true,
        "previewUrl": "http://blah-blah-blah.s3.amazonaws.com/",
```

**Comment by servocoder** [comment]
You have configured your `filemanager.config.json` correctly.

The only way to redefine client-side configuration options is the "initiate" [API method](https://github.com/servocoder/RichFilemanager-PHP/blob/master/src/Api/AwsS3Api.php#L28). I have been thinking on the capability to update options returned in this method. For example, introduce new $config["client-side"] variable to define client-side options that will be merged with the ones defined in the "initiate" method then. What do you think of this approach?
