### ISSUE TITLE
Error when deleting a file

### ISSUE THREAD

**Issue by stonino** [servocoder/RichFilemanager-PHP#35]
When deleting a file, I get php errors relating to lines 211 and 376 in \connectors\php\vendor\servocoder\richfilemanager-php\src\Repository\Local\ItemModel.php.

It seems the code is trying to retrieve mime properties and date properties of the deleted file. As I'm not a php expert, I've wrapped the lines with a if ( $this->isExists ) {}, which seems to do the trick.

**Comment by servocoder** [comment]
Hm, I can't reproduce the issue.
Can you provide a steps to reproduce?
Even better if you are able to reproduce it at the fm.devale.pro demo site.

The full error trace can help a lot as well.

**Comment by stonino** [comment]
It doesn't happen on your demo. Maybe because I'm on Windows?  I assume your demo isn't.
The error is:

PHP Warning: mime_content_type(C:/inetpub/wwwroot/dev/downloads/upload.txt): failed to open stream: No such file or directory in C:\inetpub\wwwroot\dev\fm\connectors\php\vendor\servocoder\richfilemanager-php\src\Repository\Local\ItemModel.php on line 376 PHP **Warning: filemtime(): stat failed** for C:/inetpub/wwwroot/dev/downloads/upload.txt in C:\inetpub\wwwroot\dev\fm\connectors\php\vendor\servocoder\richfilemanager-php\src\Repository\Local\ItemModel.php on line 211

If it's just me, then I can obviously live with it, as my fix seems to hold OK.

**Comment by servocoder** [comment]
It's not because of Windows. I have my local copy on Windows as well.
I think this could be a bug and I would like to reproduce it to find the reason.

Does this happen each time?
With both existing and newly uploaded files?
Or there is a specific scenary?

Also I can see that that your files folder is outside the RFM plugin folder, right?
Share you configuration, please. Only files which are deffer from the source. Possible targets: filemanager.php, config.local.php, filemanager.config.default.json.

**Comment by stonino** [comment]
I'm testing it by uploading a file and then removing it again. But also older uploaded files get the same error. 

I haven't touched config.local, as I have my config in filemanager.php. While on the subject, is there an easy way to switch to an images config? I'm using CKEditor(4) and specify a type=images in my URL, but don't know how to limit FM to only show images...


[config.local.txt](https://github.com/servocoder/RichFilemanager-PHP/files/1628401/config.local.txt)
php 7.0.13)
[filemanager.config.json.txt](https://github.com/servocoder/RichFilemanager-PHP/files/1628393/filemanager.config.json.txt)
[filemanager.php.txt](https://github.com/servocoder/RichFilemanager-PHP/files/1628394/filemanager.php.txt)

**Comment by servocoder** [comment]
Thanks for details, I will check a bit alter.

If you would like to limit RFM to serve and display the images only then limit extensions list "security.extensions.restrictions" in the [config.local.php](https://github.com/servocoder/RichFilemanager-PHP/blob/master/src/config/config.local.php) file.

If you wish to use client-side filtering (affect dispaying only) use the `?filter=image` query param in your URL as described in the [wiki article](https://github.com/servocoder/RichFilemanager/wiki/Passing-parameters-to-the-FM#restrict-the-output-with-filters)

**Comment by servocoder** [comment]
I have commited a fix for your issue.

Try the latests version of [ItemModel.php](https://github.com/servocoder/RichFilemanager-PHP/blob/master/src/Repository/Local/ItemModel.php) file and let me know if it works for you.

**Comment by servocoder** [comment]
I have pushed another commit. I don't think that it will be sufficient now to replace only the ItemModel.php file. I recommend you to replace all the repo classes to avoid errors.

**Comment by stonino** [comment]
Thanks for this. I've used the latest and everything works like a charm. Thank again.

**Comment by robsch** [comment]
Could you release this version please? The error let the client not update the UI, though the item (tried it with a folder) has been deleted.

**Comment by servocoder** [comment]
Will do at the end of this week.
If you are about to install this package separately, as I advised you in servocoder/RichFilemanager#287, then you can write the package as `"servocoder/richfilemanager-php": "dev-master"` in your `composer.json` file and it will take the latest commits.

**Comment by robsch** [comment]
@servocoder Thanks! Using dev-master is what I was trying to avoid.

**Comment by servocoder** [comment]
Released: RFM v2.7.1 + RFM-PHP v1.2.1

@robsch update to the latest version(s).

**Comment by robsch** [comment]
@servocoder Great news, thanks!
