### ISSUE TITLE
Installation and setup

### ISSUE THREAD

**Issue by wilsonld** [servocoder/RichFilemanager-PHP#4]
I am again having trouble setting up this connector on my shared ISP website (Godaddy).  I am using Windows server (IIS) and I get the message that it is unable to initialize the server.

I am succeeding in setting up on my local IIS server.  I did, however, install composer on my local machine so I think the problem might be that the remote server might not recognize the composer package manager.

Why is it so complicated to set up a simple php connector?  It now relies on a separate repository and it must be installed using composer?  Why not just have the code for the php connector contained within the filemanager repository?

Just a note that I tried the ASHX connector but there is no documentation on how to set the root directory in that connector.  It now goes to the root directory of the application and I haven't figured out how to change it to the directory that contains the uploaded filemanager server files.  Some documentation on this would be very helpful.  I am not an experienced C# programmer so I tried to convert this connector to Visual Basic but, so far, it isn't working.

Could you please provide a full PHP connector example with the appropriate config so that I can install it on my remote server (hopefully without multiple dependencies on a package manager)?

**Comment by servocoder** [comment]
> Why is it so complicated to set up a simple php connector? It now relies on a separate repository and it must be installed using composer? Why not just have the code for the php connector contained within the filemanager repository?

There were reasons to release PHP connector as a separate repository. Actually it's much more easier to install it via composer. Have you tried to perform the installation following [this guide](https://github.com/servocoder/RichFilemanager/wiki/PHP-connector)? This will install the whole RFM app including PHP connector.

> Just a note that I tried the ASHX connector but there is no documentation on how to set the root directory in that connector. It now goes to the root directory of the application and I haven't figured out how to change it to the directory that contains the uploaded filemanager server files. Some documentation on this would be very helpful. I am not an experienced C# programmer so I tried to convert this connector to Visual Basic but, so far, it isn't working.



I support the client-side and PHP connector solely. Other connectors were created by contributors which are listed [here](https://github.com/servocoder/RichFilemanager/wiki/Authors-and-Contributors). Many of them created connectors for their specific needs, so that these connectors may not support all existing features or configuration options. You can try to involve a developer/maintainer into this or a new discussion if you wish.

The most up-to-date connector is PHP, so you can use it as the reference. If you are going to improve any connector I will be highly appreciate if you with share it by creating a PR.

> Could you please provide a full PHP connector example with the appropriate config so that I can install it on my remote server (hopefully without multiple dependencies on a package manager)?

Try the wiki article link I gave you above first.

**Comment by wilsonld** [comment]
I followed the Wiki for the PHP connector and it generated an entire new RFM application with the appropriate PHP connector as documented.   I then installed the new RFM application on my local IIS server.  I then set my root directory for storage to \FileMgrFiles in the filemanager.php file in the filemanager\connectors\PHP directory as follows:

$local->setRoot("/FileMgrFiles/", true, true);

Everything worked like a charm!

I then uploaded everything to my remote shared server (Godaddy.com) and tried it.  Failed with the following message:

"Unable to perform initial request to server."

I then went back to the above filemanager.php file and attempted to set a new log file using the following coding:

$config = [
    'logger' => [
        'enabled' => true,
        'file' => '/FileMgrFiles/filemanager.log',
    ],
];

$local = new \RFM\Repository\Local\Storage($config);

Unfortunately, this doesn't seem to work as I can't get my local server to generate the new log file in the FileMgrFiles directory.  I wanted to get this working so I can upload this to the remote server to see if I can find out why RFM doesn't now work on my remote server.

I need some help in getting the new log file to generate so I can use it on my remote server and also if you have any ideas as to why RFM works fine on my local IIS server and not on a remote one.

Thanks

**Comment by servocoder** [comment]
Have you checked permissons to the RFM folder?

The same check should be performed for /FileMgrFiles/ folder. I would recommend you set permissions to 777 for /FileMgrFiles/ folder to make sure the problem not in permissions. Also you can remove 'file' parameter and just leave `'enabled' => true`. In this case logs will be written to your system temp folder which depends on your OS, see http://php.net/manual/en/function.sys-get-temp-dir.php

**Comment by wilsonld** [comment]
I checked the permissions in the /FileMgrFiles/ folder and they checked ok as writeable.  This is the same folder that serves as the server folder for filemanager and I had uploaded files to it when I was using a previous version of filemanager that worked for me on my remote servers so I am confident that it isn't a permissions issue.

I am a bit confused about the second part of your response in that writing to my system temp folder works fine (Windows 10) only if I am running filemanager on my local IIS server installed on my PC.  When I am running filemanger on the remote IIS server (Godaddy) it won't write the log file to my PC nor do I think it should.  I think this would certainly be a security risk if it were able to do so.  This is why I am attempting to get it to write the log to a file on the remote server in the /FileMgrFiles/ folder so I can then download it and take a look at what the problem might be in running filemanger on Godaddy..

**Comment by wilsonld** [comment]
In looking at this whole issue further, I think the problem is that the URL that is provided is an absolute path including the server root instead of a relative path.  This works on my local server but when I install the latest version of filemanger on my remote server it doesn't work.

In previous versions of the filemanager, the php connector returned the relative path.

To illustrate, when I select a file using the current version of filemanager and the php connector on my local server, it works fine but returns a path as follows:

http://localhost:59017/FileMgrFiles/Public/images/WestchesterPanorama.png

I have set the server root in the filemanager.php file in the connector folder as follows:

$config = [
    "options" => [
        "serverRoot" => true,
		"fileRoot" => "/FileMgrFiles/", // relative path to a storage folder of user files
		],
];

$local = new \RFM\Repository\Local\Storage($config);

According to the wiki documentation, this should give me a relative path.  When I change the server root to false, it returns the same URL.  When I change the fileroot to false, it also works but it takes me to the userfiles folder default.

The previous version of filemanager which I have installed on another site returns the following and it works on my remote server:

/FileMgrFiles/Public/images/WestchesterPanorama.png

Am I missing something in the setup in the filemanager.php file or in some other file that I should code to ensure that the URL returns a relative path without including the server root?

**Comment by servocoder** [comment]
Have you tested it at the base of IIS server? The point is that I tested it on Apache server and never atop of IIS. There were no changes in the latest version of RFM that could affect paths. So it's me depend on the config of your server.

> Am I missing something in the setup in the filemanager.php file or in some other file that I should code to ensure that the URL returns a relative path without including the server root?

If you are asking about the path to access user files, to list them out on the initial request, then your config looks correct and all should be fine. If your files are already listed correctly and you would like to change path (relative/absolute) to a particular file(s) in the list, than you have to look at `absolutePath` configuration option in the JSON configuration file.

**Comment by wilsonld** [comment]
I have done some additional testing and need to retract my theory about relative versus absolute paths.  I have tested Richfilemanger 2.2.2 which is the last version that I think returned a relative path. The result it gives me, both on my local and remote IIS servers is: 

/FileMgrFiles/Public/images/WestchesterPanorama.png

I tested version 2.3.2, however, and it seems that this version was the first version to return an absolute path.  It works both on my local server and remote server!  Version 2.3.2 returns the following on my local server:

http://localhost:59017/FileMgrFiles/Public/images/WestchesterPanorama.png

It returns the following on my remote server:

http://westchester-kensington.com/FileMgrFiles/Public/images/WestchesterPanorama.png

Since it works on both the local and remote server my conclusion is that the absolute path versus relative path difference is NOT the problem as I had suspected.  I think it probably has to do with the PHP connection refactoring that was first introduced in version 2.4.0.

I plan to do some additional testing by perhaps installing version 2.4.0 to test it on my local and remote servers.  I haven't got around to doing that yet but I will report my results when I do.

**Comment by servocoder** [comment]
Sure, test it and leave the feedback and outline the real reason. But PHP connection refactoring shouldn't bring changes in terms of paths.

**Comment by wilsonld** [comment]
I decided not to test version 2.4.0 as I suspect I will get the same result as I do with 2.5.0 and I generated the entire 2.5.0 using the composer method in the latest php connector download..  I did test 2.3.3 and it works fine on my remote server, however.  I reloaded 2.5.0 and I get the same error "unable to initiate server."

I talked to my ISP provider this morning and they don't have any ideas either.  I just wanted to scratch this possibility off my list.

One idea I have is to ask you whether the permissions for any of the folders within filemanager need to be web writable.  I have set the permissions for the folder that contains the uploaded files (FileMgrFiles) to be web writeable but I wonder if using the composer package manager requires some of the folder permissions within filemanager to be set to writeable as well, particularly as it pertains to the php connector?

Also, I still can't get the logger to go to any folder other than the default so it's difficult to trace what is happening on the remote server to cause the failure to initiate.

**Comment by wilsonld** [comment]
Update on file permissions.

I set the filemanager folder to be web writeable and all the subfolders to inherit that setting.  When I ran filemanager I still got the failure to initiate server error.  So, I don't think setting the file permissions is the answer.

I also put out an issue on GitHub composer project to ask if anyone has information on how to enable composer on a shared IIS remote server.

If I don't get any more ideas or feedback on how to resolve the problem, I guess I will have to reinstall version 2.3.3 in order to get this to work on the remote server.  This would be too bad as I always like to be able to run the latest version of the software that I've installed..

**Comment by servocoder** [comment]
I completely understand your problem, but I don't have IIS remote server to test your case. And there is nobody who could test this case among RFM contributors as far as I know.

I'll let you know, if I will find the reason. However you'd better rely on yourself.

**Comment by syracine69** [comment]
Maybe it is late to give the answer. But for the purpose of next develop.

Your problem about the error message "unable to initialize the server" as nothing to do with richfilemanager/richefilemanager-php code. The problem is inside IIS. I had the same problem with a recent installation of both of them on a Windows machine with IIS. I found somewhere in the web server log that IIS doesn't nativement handle JSON file. You have to tell somewhere in the IIS configuration that .json file (that is used in richefilemanager-php) is a application/json MIME type. Maybe you need to reboot your IIS server after. I didn't remember.

After that, running richfilemanager-php with IIS should work.

Hope that hint we help someone.
