### ISSUE TITLE
Absolute paths for thumbnails

### ISSUE THREAD

**Issue by jnvsor** [servocoder/RichFilemanager-PHP#42]
It would be nice if we could add absolute paths (Outside of the webroot) for thumbnails. Using `..` in `images.thumbnail.dir` doesn't work apparently

**Comment by servocoder** [comment]
Possible, but require a number of modifications in the code. I will take a look when I have a time for this.

**Comment by jnvsor** [comment]
Thanks :)

**Comment by servocoder** [comment]
Sorry, but I'm quite busy and have a lack of time implement this feature.
