### ISSUE TITLE
Upload to S3 not working

### ISSUE THREAD

**Issue by florent-dehanne** [servocoder/RichFilemanager-PHP#46]
Hi,

I am trying to configure RichFilemanager with Amazon S3 but i cannot achieve to upload files.

I am using this configuration :

```
$config_s3 = [
    'images' => [
        'thumbnail' => [
            'dir' => 's3_thumbs',
            'useLocalStorage' => true,
        ],
    ],
    'credentials' => [
        'region' => 'eu-west-3',
        'bucket' => 'xxxx',
        'endpoint' => null,
        'credentials' => [
            'key' => 'xxx',
            'secret' => 'xxx',
        ],
        'options' => [
            'use_path_style_endpoint' => false,
        ],
        'defaultAcl' => \RFM\Repository\S3\StorageHelper::ACL_PUBLIC_READ,
        'debug' => false,
    ],
];

$app = new \RFM\Application();
$s3 = new \RFM\Repository\S3\Storage($config_s3);
$s3->setRoot('websites', true);
$app->setStorage($s3);
$app->api = new RFM\Api\AwsS3Api();

$local = new \RFM\Repository\Local\Storage();
$app->setStorage($local);

$app->run();
```

**bucket**, **key** and **secret** are working, I can use them to connect with software like Cyberduck
Richfilemanager is working : I can display directories, view existing files and I can create folders but I can't upload new files.

In **filemanager.log** I only have this error : 
`Error code: File upload aborted, meta: {"arguments":[]}`

**Comment by servocoder** [comment]
Curious. I have just checked the upload at my AWS account and it works smoothly. Few ideas:

1. If you can create folders at S3 this most likely means the PutObject action is allowed within AWS policies. Anyway, recheck your bucket properties/policies.

2. I can see you don't set root folder for local storage explicitly. This may cause an issue, depending on your local OS/webserver permissions/policies. FYI: by default it's a "userfiles" folder of your server document root.

S3 errors are not logged into the log file yet. I'm gonna to fix this. The best thing you can do now is debug the code yourself. Let me know if you will find that the error is caused by PHP connector.

**Comment by florent-dehanne** [comment]
Thanks for your reply.

I tried to update permissions on my bucket in AWS.
In **Permissions > Access Control List > Public Access** : Write and Access are set to Everyone but upload still not working.

I've also added local configuration : 

```
$config_local = [
  'options' => [
    'serverRoot' => true,
    'fileRoot' => '/uploads/websites/'
  ]
];
$local = new \RFM\Repository\Local\Storage($config_local);
```

**Comment by servocoder** [comment]
I can't reproduce. Try to debug, or wrap the code in `filemanager.php` with `try-catch` block and echo error message.

**Comment by rakeshaspl** [comment]
I also face same above issue.

**Comment by servocoder** [comment]
> I also face same above issue.

The same request to you:

> Try to debug, or wrap the code in filemanager.php with try-catch block and echo error message.

**Comment by rakeshaspl** [comment]
this is the error I am getting.
 Warning: filesize(): stat failed for s3://fads6-test01/richFileManager/2007_285517cc25b5879e.jpg

**Comment by servocoder** [comment]
Not sure. Can you also expose the Exception trace list?

**Comment by servocoder** [comment]
There is a PR with potential fix: https://github.com/servocoder/RichFilemanager-PHP/pull/48/files

It's merged, but not versioned yet. Try to apply the fix manually and let me know if this helps for your case. Waiting for your feedback.

**Comment by agustindev** [comment]
Great, its working (Y)

**Comment by servocoder** [comment]
Awesome. It will be included in the next version.
