### ISSUE TITLE
error on upload file in Local storage

### ISSUE THREAD

**Issue by hanmuja** [servocoder/RichFilemanager-PHP#47]
Hi, when I did a upload file in local storage, the FM gived me an error message "ERROR_UPLOAD", so I investigated and I founded in Class "BaseUploadHandler" in function "get_upload_data($id)" the var $id is "upload" on upload action, but the function always return the info in @$_FILE[$id] and this array @$_FILE only have the key 'files' where is the file info what I need upload. I did a ugly change in the code for get the info in 'files' when $id is 'upload'. But I think there is a better solution for this bug.

**Comment by servocoder** [comment]
If you open the [config.local.php](https://github.com/servocoder/RichFilemanager-PHP/blob/master/src/config/config.local.php) file you can see `paramName` option in the `upload` section. All you need is to set the value to `files` in the `filemanager.php` file while configuring the RFM app.

See the original discussion: https://github.com/servocoder/RichFilemanager/issues/297

I'm also curious where the `files` value is come from?

May assume it's from CKEditor, right?

**Comment by hanmuja** [comment]
Hi, Thank you for you quick response, and the files is come from FM, I use the default multiple upload
![screenshot from 2018-05-05 17 02 45](https://user-images.githubusercontent.com/1444776/39667912-2bc9b2e2-5086-11e8-8677-762bb5df2396.png)
