### ISSUE TITLE
Enable public editing of wiki

### ISSUE THREAD

**Issue by helios-ag** [servocoder/RichFilemanager-PHP#53]
I would like to add some info about [FMRFMBundle](https://github.com/helios-ag/FMRFMBundle)
to both RichFilemanager-php and RichFilemanager wikis.

**Comment by servocoder** [comment]
You can post here the info you would like and I will add it to the `Integrations` section of the Wiki

**Comment by helios-ag** [comment]
@servocoder At this moment it would be enough to add link to FMRFMBundle as a Symfony integration.

**Comment by servocoder** [comment]
Done
