### ISSUE TITLE
ReflectionException: Class log does not exis

### ISSUE THREAD

**Issue by Chintan7027** [servocoder/RichFilemanager-PHP#9]
local.ERROR: ReflectionException: Class log does not exist in /Applications/MAMP/htdocs/s3tree/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /Applications/MAMP/htdocs/s3tree/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /Applications/MAMP/htdocs/s3tree/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /Applications/MAMP/htdocs/s3tree/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(105): Illuminate\Container\Container->make('log', Array)
#3 **/Applications/MAMP/htdocs/s3tree/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(471): app('log')**
**#4 /Applications/MAMP/htdocs/s3tree/app/filemanager/vendor/servocoder/richfilemanager-php/src/Facade/Log.php(13): logger()**
#5 /Applications/MAMP/htdocs/s3tree/app/filemanager/vendor/servocoder/richfilemanager-php/src/Repository/Local/Storage.php(93): RFM\Facade\Log::info('$this->storageR...')
#6 /Applications/MAMP/htdocs/s3tree/app/filemanager/vendor/servocoder/richfilemanager-php/src/Repository/Local/Storage.php(62): RFM\Repository\Local\Storage->setDefaults()
#7 /Applications/MAMP/htdocs/s3tree/app/Http/Controllers/S3Controller.php(26): RFM\Repository\Local\Storage->__construct(Array)
#8 [internal function]: App\Http\Controllers\S3Controller->s3file()
#9 /Applications/MAMP/htdocs/s3tree/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#10 /Applications/MAMP/htdocs/s3tree/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('s3file', Array)
#11 /Applications/MAMP/htdocs/s3tree/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\S3Controller), Object(Illuminate\Routing\Route), 's3file')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /Applications/MAMP/htdocs/s3tree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

**Comment by servocoder** [comment]
provide more info about your background

**Comment by Chintan7027** [comment]
I am using Laravel 5.2 and package added in composer.json file by 

 "autoload": {
        "classmap": [
            "database",
            "app/filemanager"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },

so app\/filemanager contains this library, initially i have installed by composer but the same error i was getting that's why the different method i have tried. 

Thanks for your support

**Comment by servocoder** [comment]
Not sure about Laravel, perhaps I will be able to try RFM with Laravel on this weekend.

**Comment by Chintan7027** [comment]
Yes sure, 
This will help to Laravel community
Thanks

**Comment by servocoder** [comment]
I believe this issue is related to the #10 that was fixed.
Feel free to reopen the issue if you still experience problems.
